### ISSUE TITLE
Typo + Batching question

### ISSUE THREAD

**Issue by stergiosba** [mvcisback/gatv2_eqx#1]
You have a typo here:
https://github.com/mvcisback/gatv2_eqx/blob/8965baecf4d0504cf2fa840e9dcf1c2c14cab424/src/gatv2_eqx/model.py#L76

Are you facing problems with keeping the batch constant here:
https://github.com/mvcisback/gatv2_eqx/blob/8965baecf4d0504cf2fa840e9dcf1c2c14cab424/examples/train_dict_lookup.py#L84

**Comment by mvcisback** [comment]
Good catch! And yes, that's the part I plan to re-write to batch -- although I figured it'd be better to do it the "dumb way" first to make sure it can actually fit to the test problem.
